/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculadoraJava;

public class App {
    public static void main(String[] args) {
        
        Calculadora operacao = new Calculadora();
        
        System.out.println("______________________________");
        System.out.println("Calculando operacoes em Java!!");
        System.out.println("______________________________");
        
        System.out.print("Soma: ");
        System.out.println(operacao.soma(10, 3));
        
        System.out.print("Subtracao: ");
        System.out.println(operacao.subtracao(25, 12));
        
        System.out.print("Multiplicacao: ");
        System.out.println(operacao.multiplicacao(1, 13));
        
        System.out.print("Divisao: ");
        System.out.println(operacao.divisao(130, 10));
        
        System.out.print("Potencia: ");
        System.out.println(operacao.potencia(6, 2));
        
        System.out.print("Porcentagem: ");
        System.out.println(operacao.porcentagem(100, 8));
             
        System.out.print("Raiz Quadrada: ");
        System.out.println(operacao.raizQ(64));
        System.out.println("______________________________");
        System.out.println("Calculadora simples em Java");
        System.out.println("______________________________");
    }
}